# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setDockNestingEnabled(False)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.videoPreview = QtWidgets.QLabel(self.centralWidget)
        self.videoPreview.setGeometry(QtCore.QRect(0, 0, 960, 540))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoPreview.sizePolicy().hasHeightForWidth())
        self.videoPreview.setSizePolicy(sizePolicy)
        self.videoPreview.setFrameShape(QtWidgets.QFrame.Box)
        self.videoPreview.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.videoPreview.setMidLineWidth(1)
        self.videoPreview.setObjectName("videoPreview")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(970, 10, 300, 111))
        self.groupBox.setObjectName("groupBox")
        self.pushBtn_Video = QtWidgets.QPushButton(self.groupBox)
        self.pushBtn_Video.setGeometry(QtCore.QRect(10, 30, 281, 40))
        self.pushBtn_Video.setCheckable(False)
        self.pushBtn_Video.setObjectName("pushBtn_Video")
        self.check_proc = QtWidgets.QCheckBox(self.groupBox)
        self.check_proc.setGeometry(QtCore.QRect(10, 70, 110, 40))
        self.check_proc.setObjectName("check_proc")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(970, 539, 300, 191))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushBtn_Map = QtWidgets.QPushButton(self.groupBox_2)
        self.pushBtn_Map.setGeometry(QtCore.QRect(10, 140, 281, 40))
        self.pushBtn_Map.setCheckable(False)
        self.pushBtn_Map.setObjectName("pushBtn_Map")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 540, 960, 190))
        self.groupBox_3.setObjectName("groupBox_3")
        self.iot_widget = QtWidgets.QWidget(self.groupBox_3)
        self.iot_widget.setGeometry(QtCore.QRect(5, 25, 800, 160))
        self.iot_widget.setObjectName("iot_widget")
        self.temp_label = QtWidgets.QLabel(self.groupBox_3)
        self.temp_label.setGeometry(QtCore.QRect(850, 36, 100, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.temp_label.setFont(font)
        self.temp_label.setObjectName("temp_label")
        self.humid_label = QtWidgets.QLabel(self.groupBox_3)
        self.humid_label.setGeometry(QtCore.QRect(850, 90, 100, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.humid_label.setFont(font)
        self.humid_label.setObjectName("humid_label")
        self.co_label = QtWidgets.QLabel(self.groupBox_3)
        self.co_label.setGeometry(QtCore.QRect(850, 150, 100, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.co_label.setFont(font)
        self.co_label.setObjectName("co_label")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_4.setGeometry(QtCore.QRect(970, 130, 301, 401))
        self.groupBox_4.setObjectName("groupBox_4")
        self.cB_Bell = QtWidgets.QCheckBox(self.groupBox_4)
        self.cB_Bell.setEnabled(False)
        self.cB_Bell.setGeometry(QtCore.QRect(20, 40, 92, 23))
        self.cB_Bell.setCheckable(True)
        self.cB_Bell.setObjectName("cB_Bell")
        self.cB_SMS = QtWidgets.QCheckBox(self.groupBox_4)
        self.cB_SMS.setGeometry(QtCore.QRect(20, 70, 92, 23))
        self.cB_SMS.setChecked(True)
        self.cB_SMS.setObjectName("cB_SMS")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_4)
        self.tableWidget.setGeometry(QtCore.QRect(20, 110, 261, 211))
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(120)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.videoPreview.setText(_translate("MainWindow", "Video Preview"))
        self.groupBox.setTitle(_translate("MainWindow", "IP Camera"))
        self.pushBtn_Video.setText(_translate("MainWindow", "Open Streams"))
        self.check_proc.setText(_translate("MainWindow", "Processing"))
        self.groupBox_2.setTitle(_translate("MainWindow", "General Settings"))
        self.pushBtn_Map.setText(_translate("MainWindow", "Display Map"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Sensor Preview"))
        self.temp_label.setText(_translate("MainWindow", "T:"))
        self.humid_label.setText(_translate("MainWindow", "H:"))
        self.co_label.setText(_translate("MainWindow", "CO:"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Notification"))
        self.cB_Bell.setText(_translate("MainWindow", "Bell"))
        self.cB_SMS.setText(_translate("MainWindow", "SMS"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Tel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
